import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl

mpl.rc('font', **{'family': 'serif', 'serif': ['Computer Modern'], 'size': 14})
mpl.rc('text', usetex=True)

M = np.genfromtxt('data/E_b.txt')
N = np.genfromtxt('data/E_a.txt')
L = np.genfromtxt('data/E_c.txt')
Psi_a = np.genfromtxt('data/phi_a.txt')
Psi_b = np.genfromtxt('data/phi_b.txt')
Psi_b_ana = np.genfromtxt('data/phi_analytisch.txt')
Psi_c = np.genfromtxt('data/phi_c.txt')


figure, ax = plt.subplots()
plt.figure(figsize=(7,7))
plt.title(r'E-Feld')
plt.imshow(M, interpolation='kaiser')
plt.xlabel(r'$y$')
plt.ylabel(r'$x$')
plt.tight_layout()
plt.gca().set_xticks(np.arange(-1 , len(M), len(M)))
plt.gca().set_yticks(np.arange(-1 , len(M), len(M)))
plt.gca().set_xticklabels(np.arange(0, 2, 1))
plt.gca().set_yticklabels(np.arange(0, 2, 1))
plt.colorbar()
plt.savefig('figures/E_b.pdf')

plt.cla()
plt.clf()

figure, ax = plt.subplots()
plt.figure(figsize=(7,7))
plt.title(r'E-Feld')
plt.imshow(N, interpolation='kaiser')
plt.xlabel(r'$y$')
plt.ylabel(r'$x$')
plt.tight_layout()
plt.gca().set_xticks(np.arange(-1 , len(N), len(N)))
plt.gca().set_yticks(np.arange(-1 , len(N), len(N)))
plt.gca().set_xticklabels(np.arange(0, 2, 1))
plt.gca().set_yticklabels(np.arange(0, 2, 1))
plt.colorbar()
plt.savefig('figures/E_a.pdf')

plt.cla()
plt.clf()

figure, ax = plt.subplots()
plt.figure(figsize=(7,7))
plt.title(r'E-Feld')
plt.imshow(L, interpolation='kaiser')
plt.xlabel(r'$y$')
plt.ylabel(r'$x$')
plt.tight_layout()
plt.gca().set_xticks(np.arange(-1 , len(L), len(L)))
plt.gca().set_yticks(np.arange(-1 , len(L), len(L)))
plt.gca().set_xticklabels(np.arange(0, 2, 1))
plt.gca().set_yticklabels(np.arange(0, 2, 1))
plt.colorbar()
plt.savefig('figures/E_c.pdf')

plt.cla()
plt.clf()

figure, ax = plt.subplots()
plt.figure(figsize=(7,7))
plt.title(r'$\Phi(x,y)$')
plt.imshow(Psi_a, interpolation='kaiser')
plt.xlabel(r'$y$')
plt.ylabel(r'$x$')
plt.tight_layout()
plt.gca().set_xticks(np.arange(-1 , len(Psi_a), len(Psi_a)))
plt.gca().set_yticks(np.arange(-1 , len(Psi_a), len(Psi_a)))
plt.gca().set_xticklabels(np.arange(0, 2, 1))
plt.gca().set_yticklabels(np.arange(0, 2, 1))
plt.colorbar()
plt.savefig('figures/Phi_a.pdf')

plt.cla()
plt.clf()

figure, ax = plt.subplots()
plt.figure(figsize=(7,7))
plt.title(r'$\Phi(x,y)$')
plt.imshow(Psi_b, interpolation='kaiser')
plt.xlabel(r'$y$')
plt.ylabel(r'$x$')
plt.tight_layout()
plt.gca().set_xticks(np.arange(-1 , len(Psi_b), len(Psi_b)))
plt.gca().set_yticks(np.arange(-1 , len(Psi_b), len(Psi_b)))
plt.gca().set_xticklabels(np.arange(0, 2, 1))
plt.gca().set_yticklabels(np.arange(0, 2, 1))
plt.colorbar()
plt.savefig('figures/Phi_b.pdf')

plt.cla()
plt.clf()
figure, ax = plt.subplots()
plt.figure(figsize=(7,7))
plt.title(r'$\Phi(x,y)$')
plt.imshow(Psi_c, interpolation='kaiser')
plt.xlabel(r'$y$')
plt.ylabel(r'$x$')
plt.tight_layout()
plt.gca().set_xticks(np.arange(-1 , len(Psi_c), len(Psi_c)))
plt.gca().set_yticks(np.arange(-1 , len(Psi_c), len(Psi_c)))
plt.gca().set_xticklabels(np.arange(0, 2, 1))
plt.gca().set_yticklabels(np.arange(0, 2, 1))
plt.colorbar()
plt.savefig('figures/Phi_c.pdf')

plt.cla()
plt.clf()

figure, ax = plt.subplots()
plt.figure(figsize=(7,7))
plt.title(r'$\Phi(x,y)$ analytisch')
plt.imshow(Psi_b_ana, interpolation='kaiser')
plt.xlabel(r'$y$')
plt.ylabel(r'$x$')
plt.tight_layout()
plt.gca().set_xticks(np.arange(-1 , len(Psi_b_ana), len(Psi_b_ana)))
plt.gca().set_yticks(np.arange(-1 , len(Psi_b_ana), len(Psi_b_ana)))
plt.gca().set_xticklabels(np.arange(0, 2, 1))
plt.gca().set_yticklabels(np.arange(0, 2, 1))
plt.colorbar()
plt.savefig('figures/Phi_b_ana.pdf')
